services:
  payments_dashboard:
    container_name: payments_dashboard
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '4321:4321'
    networks:
      - main
    volumes:
      - ./src:/app/src
      - ./public:/app/public

networks:
  main:
    driver: bridge
    external: true